#!/usr/bin/env python3
"""Build the plain-text Markdown mirror of every page, plus public/llms.txt, from the HTML in public/.

Run after editing any page:              python3 tools/build_markdown.py
Fail if a mirror is out of date (CI):    python3 tools/build_markdown.py --check

It also writes the mirrors' block in netlify.toml: served as text/plain; charset=utf-8, so every
browser shows them inline with the curly quotes intact, with a canonical Link header pointing at
the HTML page (and noindex where the HTML page is noindex).

Each page gets a mirror at its name + .md: public/privacy/index.html -> public/privacy.md,
public/index.html -> public/index.md, public/404.html -> public/404.md. /accessibility/ promises
them to visitors, and AI tools read them in place of the HTML.

Written to be read aloud and read as raw text: one idea per line, headings in page order, tables
turned into lists (a screen reader reads a pipe table cell by cell with no headers), link text
kept with the full address, no decorative markup. Only <main> and the footer are copied; the
header, logo, icons and scripts are left out. public/admin/ is the owner's checklist and gets none.
Standard library only.
"""

import re
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
NETLIFY = ROOT / "netlify.toml"
NETLIFY_BEGIN = "# BEGIN plain-text mirrors: generated by tools/build_markdown.py, do not edit by hand"
NETLIFY_END = "# END plain-text mirrors"
SITE_ORIGIN = "https://tech-savvies.com"

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}
BLOCK = {"address", "article", "aside", "div", "figure", "footer", "form", "h1", "h2", "h3", "h4", "h5", "h6",
         "header", "main", "nav", "ol", "p", "section", "table", "ul"}
SKIP = {"script", "style", "svg", "button", "template", "noscript"}
NEW_TAB = "(opens in a new tab)"


class Node:
    def __init__(self, tag, attrs=None, parent=None):
        self.tag = tag
        self.attrs = dict(attrs or [])
        self.children = []
        self.parent = parent

    def classes(self):
        return (self.attrs.get("class") or "").split()

    def find_all(self, pred):
        for child in self.children:
            if isinstance(child, Node):
                if pred(child):
                    yield child
                yield from child.find_all(pred)

    def find(self, pred):
        return next(self.find_all(pred), None)

    def text(self):
        return "".join(c if isinstance(c, str) else c.text() for c in self.children)


class TreeBuilder(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node("#root")
        self.cur = self.root

    def handle_starttag(self, tag, attrs):
        node = Node(tag, attrs, self.cur)
        self.cur.children.append(node)
        if tag not in VOID:
            self.cur = node

    def handle_startendtag(self, tag, attrs):
        self.cur.children.append(Node(tag, attrs, self.cur))

    def handle_endtag(self, tag):
        node = self.cur
        while node is not self.root and node.tag != tag:
            node = node.parent
        if node is not self.root:
            self.cur = node.parent

    def handle_data(self, data):
        self.cur.children.append(data)


def squash(text):
    return re.sub(r"\s+", " ", text).strip()


def escape(text):
    return re.sub(r"([\\`*_\[\]])", r"\\\1", text)


def absolute(url, page_url):
    if url.startswith("#"):
        return page_url + url
    if url.startswith("/") and not url.startswith("//"):
        return SITE_ORIGIN + url
    return url


class Renderer:
    def __init__(self, page_url):
        self.page_url = page_url

    # ---- inline ----
    def inline(self, node):
        out = []
        for child in node.children:
            if isinstance(child, str):
                out.append(escape(child))
                continue
            tag = child.tag
            if tag in SKIP or tag == "img":
                continue
            if "visually-hidden" in child.classes() and squash(child.text()) == NEW_TAB:
                continue  # the mirror opens nothing in a new tab
            if tag == "br":
                out.append(" ")
            elif tag == "a":
                text = squash(self.inline(child))
                href = absolute(child.attrs.get("href", ""), self.page_url)
                out.append("[%s](%s)" % (text, href))
            elif tag in ("strong", "b"):
                out.append("**%s**" % squash(self.inline(child)))
            elif tag in ("em", "i"):
                out.append("*%s*" % squash(self.inline(child)))
            elif "price-amount" in child.classes():
                out.append("**%s**:" % squash(self.inline(child)))
            else:
                out.append(self.inline(child))
        return "".join(out)

    # ---- blocks ----
    def blocks(self, node, depth=0):
        """Return a list of Markdown blocks for node's children."""
        out, run = [], []
        label = []  # a p.contact-label ("Direct Email:") is joined to the value after it

        def emit(blocks):
            if label and blocks:
                blocks = ["**%s** %s" % (label.pop(), blocks[0])] + blocks[1:]
            out.extend(blocks)

        def flush():
            text = squash("".join(run))
            if text:
                emit([text])
            run.clear()

        for child in node.children:
            if isinstance(child, str):
                run.append(escape(child))
                continue
            if child.tag in SKIP or "hidden-field" in child.classes() or child.attrs.get("hidden") is not None:
                continue
            if child.tag == "p" and "contact-label" in child.classes():
                flush()
                label.append(squash(self.inline(child)))
            elif child.tag in BLOCK or child.tag in ("img", "li"):
                flush()
                emit(self.block(child, depth))
            else:
                run.append(self.inline(_wrap(child)))
        flush()
        return out

    def block(self, node, depth):
        tag = node.tag
        if re.fullmatch(r"h[1-6]", tag):
            return ["%s %s" % ("#" * int(tag[1]), squash(self.inline(node)))]
        if tag == "p":
            text = squash(self.inline(node))
            return [text] if text else []
        if tag in ("ul", "ol"):
            return [self.list(node, depth)]
        if tag == "table":
            return self.table(node)
        if tag == "form":
            return self.form(node)
        if tag == "img":
            alt = squash(node.attrs.get("alt", ""))
            return ["![%s](%s)" % (escape(alt), absolute(node.attrs.get("src", ""), self.page_url))] if alt else []
        return self.blocks(node, depth)

    def list(self, node, depth):
        lines = []
        for i, li in enumerate(c for c in node.children if isinstance(c, Node) and c.tag == "li"):
            # A list item that holds its own heading is a section (the home page offers): no bullet
            if li.find(lambda n: re.fullmatch(r"h[1-6]", n.tag)):
                lines.append("\n\n".join(self.blocks(li, depth)))
                continue
            marker = "%d." % (i + 1) if node.tag == "ol" else "-"
            parts = self.blocks(li, depth + 1)
            first, rest = (parts[0] if parts else ""), parts[1:]
            item = "  " * depth + marker + " " + first
            for extra in rest:
                item += "\n" + extra
            lines.append(item)
        sep = "\n\n" if any("\n\n" in l or l.startswith("#") for l in lines) else "\n"
        return sep.join(lines)

    def table(self, node):
        """A table becomes one list item per row, each cell labelled with its column header."""
        caption = node.find(lambda n: n.tag == "caption")
        heads = [squash(self.inline(th)) for th in node.find_all(lambda n: n.tag == "th" and n.attrs.get("scope") == "col")]
        body = node.find(lambda n: n.tag == "tbody") or node
        out = []
        if caption:
            out.append("%s:" % squash(self.inline(caption)))
        rows = []
        for tr in body.find_all(lambda n: n.tag == "tr"):
            cells = [c for c in tr.children if isinstance(c, Node) and c.tag in ("th", "td")]
            if not cells:
                continue
            item = "- **%s**" % squash(self.inline(cells[0]))
            for head, cell in zip(heads[1:], cells[1:]):
                item += "\n  - %s: %s" % (head, squash(self.inline(cell)))
            rows.append(item)
        out.append("\n".join(rows))
        return out

    def form(self, node):
        """Forms can't be filled in here: point to the web page and list what the form asks for."""
        notes = [p for p in node.find_all(lambda n: n.tag == "p" and "form-note" in n.classes())]
        first = [p for p in notes if p.attrs.get("id") == "form-required"]
        out = ["The contact form works on the web page only: %s." % self.page_url]
        out += [squash(self.inline(p)) for p in first]
        out.append("It asks for:")
        fields = []
        for label in node.find_all(lambda n: n.tag == "label"):
            if label.find(lambda n: n.tag == "input") is not None:
                continue  # the honeypot label wraps its input
            text = squash(self.inline(label))
            field = node.find(lambda n: n.attrs.get("id") == label.attrs.get("for"))
            if field is not None and field.tag == "select":
                options = [squash(o.text()) for o in field.find_all(lambda n: n.tag == "option") if o.attrs.get("value") != ""]
                text += " Choose one: " + ", ".join(escape(o) for o in options) + "."
            fields.append("- " + text)
        out.append("\n".join(fields))
        out += [squash(self.inline(p)) for p in notes if p not in first]
        return out


def _wrap(node):
    wrapper = Node("#wrap")
    wrapper.children = [node]
    return wrapper


def mirror_path(html_path):
    rel = html_path.relative_to(PUBLIC)
    if rel.name == "index.html":
        return PUBLIC / ("index.md" if rel.parent == Path(".") else str(rel.parent) + ".md")
    return PUBLIC / rel.with_suffix(".md")


def page_url(html_path):
    rel = html_path.relative_to(PUBLIC).as_posix()
    if rel == "index.html":
        return SITE_ORIGIN + "/"
    if rel.endswith("/index.html"):
        return SITE_ORIGIN + "/" + rel[: -len("index.html")]
    return SITE_ORIGIN + "/" + rel


def mirror_url(html_path):
    return SITE_ORIGIN + "/" + mirror_path(html_path).relative_to(PUBLIC).as_posix()


def pages():
    return sorted(p for p in PUBLIC.rglob("*.html") if p.relative_to(PUBLIC).parts[0] != "admin")


def meta(root, name):
    node = root.find(lambda n: n.tag == "meta" and n.attrs.get("name") == name)
    return squash(node.attrs.get("content", "")) if node else ""


def parse(html_path):
    builder = TreeBuilder()
    builder.feed(html_path.read_text(encoding="utf-8"))
    builder.close()
    return builder.root


def separate_lists(blocks):
    """Two lists in a row with the same marker are one list in Markdown; switch the second to "*"."""
    out = []
    for block in blocks:
        if out and block.startswith("- ") and out[-1].startswith("- "):
            block = re.sub(r"(?m)^- ", "* ", block)
        out.append(block)
    return out


def render(html_path):
    root = parse(html_path)
    url = page_url(html_path)
    r = Renderer(url)
    main = root.find(lambda n: n.tag == "main")
    footer = root.find(lambda n: n.tag == "footer")
    title = squash(root.find(lambda n: n.tag == "title").text())
    description = meta(root, "description")

    body = r.blocks(main)
    if not body or not body[0].startswith("# "):
        sys.exit("build_markdown: %s: <main> must start with its h1" % html_path)
    intro = ["Plain-text version of the web page “%s” at %s." % (escape(title), url)]
    if description:
        intro.append("Summary: " + escape(description))

    foot = []
    if footer is not None:
        brand = footer.find(lambda n: "footer-brand" in n.classes())
        if brand is not None:
            brand.parent.children.remove(brand)
        foot = r.blocks(footer)

    parts = separate_lists([body[0]] + intro + body[1:] + ["---"] + foot)
    return "\n\n".join(parts) + "\n"


def render_llms():
    """llms.txt (llmstxt.org): what the site is, then a link to each indexable page's mirror."""
    home = parse(PUBLIC / "index.html")
    groups = {"Pages": [], "Legal": []}
    legal = {"terms", "refunds", "privacy", "cookies", "accessibility"}
    # Same order as the footer links on the home page
    order = [a.attrs.get("href") for a in home.find(lambda n: n.tag == "footer").find_all(lambda n: n.tag == "a")]
    position = lambda path: order.index(page_url(path)[len(SITE_ORIGIN):]) if page_url(path)[len(SITE_ORIGIN):] in order else len(order)
    for path in sorted(pages(), key=position):
        root = parse(path)
        if "noindex" in meta(root, "robots"):
            continue
        title = squash(root.find(lambda n: n.tag == "title").text()).split(" | ")[0]
        if path.relative_to(PUBLIC).as_posix() == "index.html":
            title = "Home"
        group = "Legal" if path.relative_to(PUBLIC).parts[0] in legal else "Pages"
        groups[group].append("- [%s](%s): %s" % (title, mirror_url(path), meta(root, "description")))
    lines = [
        "# Tech-Savvies",
        "",
        "> %s" % meta(home, "description"),
        "",
        "Tech-Savvies is the trading name of Peter Parizhsky, a sole proprietor based in New York, NY, "
        "working with clients anywhere, remotely. Contact: info@tech-savvies.com. Each link below is the "
        "plain-text Markdown version of a page; the HTML page is the canonical one, at the same address "
        "without .md (the home page is %s/)." % SITE_ORIGIN,
        "",
    ]
    for group, items in groups.items():
        lines += ["## " + group, ""] + items + [""]
    return "\n".join(lines)


def render_netlify():
    blocks = [NETLIFY_BEGIN]
    for path in pages():
        root = parse(path)
        values = ['    Content-Type = "text/plain; charset=utf-8"']
        if "noindex" in meta(root, "robots"):
            values.append('    X-Robots-Tag = "noindex"')
        else:
            values.append('    Link = "<%s>; rel=\\"canonical\\""' % page_url(path))
        blocks += ["[[headers]]", '  for = "/%s"' % mirror_path(path).relative_to(PUBLIC).as_posix(), "  [headers.values]"] + values + [""]
    blocks += ["[[headers]]", '  for = "/llms.txt"', "  [headers.values]", '    Content-Type = "text/plain; charset=utf-8"', NETLIFY_END]
    text = NETLIFY.read_text(encoding="utf-8")
    section = "\n".join(blocks)
    if NETLIFY_BEGIN in text:
        return re.sub(re.escape(NETLIFY_BEGIN) + ".*?" + re.escape(NETLIFY_END), lambda m: section, text, flags=re.S)
    return text.rstrip("\n") + "\n\n" + section + "\n"


def outputs():
    files = {mirror_path(p): render(p) for p in pages()}
    files[PUBLIC / "llms.txt"] = render_llms()
    files[NETLIFY] = render_netlify()
    return files


def main(argv):
    check = "--check" in argv
    stale = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.write_text(text, encoding="utf-8")
            print("wrote", path.relative_to(ROOT).as_posix())
    if stale:
        print("out of date (run python3 tools/build_markdown.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
